# Generated by Django 4.2.10 on 2025-09-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0014_alter_estimated_cost_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestsubmit',
            name='submission_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
