# Generated by Django 4.2.10 on 2025-10-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0011_program_travel_users_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='no_approval_team',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Four'), (2, 'Three')], null=True),
        ),
    ]
