# Generated by Django 4.2.26 on 2025-12-06 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_profile_emp_id_profile_field_office'),
        ('program', '0012_program_no_approval_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarmUserRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_officer', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.profile')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='program.program')),
            ],
        ),
    ]
