# Generated by Django 4.2.26 on 2025-12-06 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_profile_emp_id_profile_field_office'),
        ('program', '0013_carmuserroles'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='carm_users_role',
            field=models.ManyToManyField(blank=True, related_name='carmuserroles', through='program.CarmUserRoles', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='carmuserroles',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='carm_profile', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='carmuserroles',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='carm_program', to='program.program'),
        ),
        migrations.AlterField(
            model_name='program',
            name='travel_users_role',
            field=models.ManyToManyField(blank=True, related_name='traveluserroles', through='program.TravelUserRoles', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='traveluserroles',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='travel_profile', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='traveluserroles',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='travel_program', to='program.program'),
        ),
    ]
