# Generated by Django 4.2.26 on 2025-12-05 18:54

import carm.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0006_remove_portfolio_is_involved_cn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('program', '0012_program_no_approval_team'),
        ('app_admin', '0009_feedback_resolution_feedback_response_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_feedback_recieved', models.DateField(blank=True, null=True)),
                ('published_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('feedback_channel_other', models.TextField(blank=True, null=True)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to=carm.models.path_and_rename)),
                ('informant_name', models.TextField(blank=True, null=True)),
                ('informant_location_other', models.TextField(blank=True, null=True)),
                ('informant_contact_phone_number', models.TextField(blank=True, null=True)),
                ('informant_contact_other', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback_Status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_admin.feedback_status')),
                ('feedback_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_admin.feedback_category')),
                ('feedback_channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_admin.feedback_channel')),
                ('informant_age', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_admin.informant_age')),
                ('informant_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_admin.woreda')),
                ('informant_sex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_admin.informant_gender')),
                ('informant_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_admin.informant_status')),
                ('informed_consent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_admin.informed_consent')),
                ('office_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_admin.fieldoffice')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portfolio.portfolio')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='program.program')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='feedback_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-published_date',),
            },
        ),
        migrations.CreateModel(
            name='Processing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_date', models.DateField(blank=True, null=True)),
                ('feedback_referred', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Yes'), (2, 'No')], default=1, null=True)),
                ('feedback_shared', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Yes'), (2, 'No')], default=1, null=True)),
                ('feedback_shared_with', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Internally'), (2, 'Externally')], null=True)),
                ('feedback_shared_with_note', models.TextField(blank=True, null=True)),
                ('feedback_referred_to', models.TextField(blank=True, null=True)),
                ('types_of_response_required_other', models.TextField(blank=True, null=True)),
                ('action_followup_required', models.BooleanField(blank=True, default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carm.feedback')),
                ('types_of_response_required', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_admin.feedback_response_type')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='processing_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-processing_date',),
            },
        ),
        migrations.CreateModel(
            name='Closing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_taken_other', models.TextField(blank=True, null=True)),
                ('response_provided', models.BooleanField(default=False)),
                ('response_date', models.DateField(blank=True, null=True)),
                ('response_summary', models.TextField(blank=True, null=True)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('feedback_checked_reviewed', models.BooleanField(default=False)),
                ('date_reviewed', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_taken', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_admin.feedback_response_type')),
                ('action_taken_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='action_taken_by', to=settings.AUTH_USER_MODEL)),
                ('feedback', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carm.feedback')),
                ('resolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_admin.feedback_resolution')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='closing_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-closing_date',),
            },
        ),
    ]
