# Generated by Django 4.2.26 on 2025-12-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processing',
            name='action_fu_required',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Yes'), (2, 'No')], default=1, null=True),
        ),
    ]
