# Generated by Django 4.2.26 on 2025-12-05 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carm', '0002_processing_action_fu_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processing',
            name='action_followup_required',
        ),
    ]
