# Generated by Django 4.2.26 on 2025-12-05 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carm', '0003_remove_processing_action_followup_required'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processing',
            old_name='action_fu_required',
            new_name='action_followup_needed',
        ),
    ]
