# Generated by Django 4.2.26 on 2025-12-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carm', '0004_rename_action_fu_required_processing_action_followup_needed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processing',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='closing',
            name='responses_provided',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Yes'), (2, 'No')], default=1, null=True),
        ),
    ]
