# Generated by Django 4.2.26 on 2025-12-06 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carm', '0005_alter_processing_options_closing_responses_provided'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closing',
            name='response_provided',
        ),
    ]
