# Generated by Django 4.2.26 on 2025-12-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carm', '0006_remove_closing_response_provided'),
    ]

    operations = [
        migrations.AddField(
            model_name='closing',
            name='feedback_closed',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Yes'), (2, 'No')], default=1, null=True),
        ),
    ]
