# Generated by Django 4.2.10 on 2025-09-13 13:23

import django.core.validators
from django.db import migrations, models
import report.models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0015_alter_activityreportimpact_actual_impact_pilot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityreportdocument',
            name='document',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=report.models.path_and_rename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='icnreportdocument',
            name='document',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=report.models.path_and_rename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf'])]),
        ),
    ]
