# Generated by Django 4.2.10 on 2025-09-13 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conceptnote', '0042_alter_disaggregate_options_alter_impact_options'),
        ('report', '0016_alter_activityreportdocument_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcnReportDisaggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_pilot', models.FloatField(blank=True, null=True)),
                ('actual_scalup', models.FloatField(blank=True, null=True)),
                ('disaggregate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conceptnote.disaggregate')),
                ('icnreport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.icnreport')),
                ('impact', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conceptnote.impact')),
            ],
        ),
    ]
