# Generated by Django 4.2.10 on 2025-09-14 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0017_icnreportdisaggregate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icnreportdisaggregate',
            old_name='actual_scalup',
            new_name='actual_scaleup',
        ),
    ]
