# Generated by Django 4.2.10 on 2025-09-14 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conceptnote', '0042_alter_disaggregate_options_alter_impact_options'),
        ('report', '0018_rename_actual_scalup_icnreportdisaggregate_actual_scaleup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icnreportdisaggregate',
            name='impact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conceptnote.impact'),
        ),
    ]
