# Generated by Django 4.2.10 on 2025-10-22 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0019_alter_icnreportdisaggregate_impact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icnreportimpact',
            options={'ordering': ('id',)},
        ),
    ]
