# Generated by Django 4.2.26 on 2026-01-06 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conceptnote', '0045_alter_activityimpact_options'),
        ('report', '0020_alter_icnreportimpact_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityReportDisaggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_pilot', models.FloatField(blank=True, null=True)),
                ('actual_scaleup', models.FloatField(blank=True, null=True)),
                ('activityimpact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conceptnote.activityimpact')),
                ('activityreport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report.activityreport')),
                ('disaggregate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conceptnote.activitydisaggregate')),
            ],
        ),
    ]
