# Generated by Django 4.2.26 on 2025-12-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0008_informant_status_informed_consent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback_Resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback_Response_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='woreda',
            options={'ordering': ('name',)},
        ),
    ]
