# Generated by Django 4.2.10 on 2025-09-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_portfolio_title_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='is_involved_cn',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
