# Generated by Django 4.2.10 on 2025-09-07 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_portfolio_is_involved_cn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='is_involved_cn',
        ),
    ]
