# Generated by Django 4.2.10 on 2025-09-13 13:23

import conceptnote.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conceptnote', '0039_alter_activityimpact_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='impact',
            name='is_disaggregate',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='activitydocument',
            name='document',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=conceptnote.models.path_and_rename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf'])]),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=conceptnote.models.path_and_rename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf'])]),
        ),
    ]
