# Generated by Django 4.2.10 on 2025-09-13 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conceptnote', '0040_impact_is_disaggregate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disaggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('pilot', models.FloatField(blank=True, null=True)),
                ('scaleup', models.FloatField(blank=True, null=True)),
                ('impact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conceptnote.impact')),
            ],
        ),
    ]
