# Generated by Django 4.2.10 on 2025-09-13 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conceptnote', '0041_disaggregate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disaggregate',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='impact',
            options={'ordering': ('id',)},
        ),
    ]
