# Generated by Django 5.2.8 on 2025-11-21 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conceptnote', '0042_alter_disaggregate_options_alter_impact_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icnsubmitapproval_t',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='icnsubmitapproval_t',
            name='document',
        ),
        migrations.RemoveField(
            model_name='icnsubmitapproval_t',
            name='submit_id',
        ),
        migrations.RemoveField(
            model_name='icnsubmitapproval_t',
            name='user',
        ),
        migrations.DeleteModel(
            name='ActivitySubmitApproval_T',
        ),
        migrations.DeleteModel(
            name='IcnSubmitApproval_T',
        ),
    ]
