# Generated by Django 4.2.26 on 2025-12-13 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conceptnote', '0043_remove_icnsubmitapproval_t_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityimpact',
            name='is_disaggregate',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name='ActivityDisaggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('pilot', models.FloatField(blank=True, null=True)),
                ('scaleup', models.FloatField(blank=True, null=True)),
                ('impact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conceptnote.activityimpact')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
