# Generated by Django 4.2.26 on 2025-12-14 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conceptnote', '0044_activityimpact_is_disaggregate_activitydisaggregate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityimpact',
            options={'ordering': ('id',)},
        ),
    ]
