# Generated by Django 4.2.26 on 2025-12-13 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_profile_emp_id_profile_field_office'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('first_name',)},
        ),
    ]
